### ISSUE TITLE
Missing Dimension information for Communications Tab

### ISSUE THREAD

**Issue by clapierre** [w3c/maturity-model#189]
In tab 3.1 Communications cell A6 is blank.
Every other dimension has a description of what the dimension is.
Eg.
3.2 K&S has

> Internal and external personnel at all levels of an organization should have accessibility knowledge and skills relevant to their organizational role. Accessibility knowledge and skills relevant to each individual’s position helps employees understand their part in achieving the organization's accessibility goals.

3.3 Support has

> Support for internal employees and external customers with disabilities. This includes reasonable accommodations for employees and customer support that is specific to users' accessibility needs.

etc.

**Comment by Helixopp** [comment]
@clapierre is this issue still present? Or can we resolve it with the latest June draft?

**Comment by clapierre** [comment]
Still and issue @Helixopp

**Comment by jeffkline** [comment]
Copied the definition of Communications dimension in 3.1 into cell Communications Tab  at cell A6 which now reads:

Communications need to be accessible to the widest audience possible and meet the requirements in the accessibility standards. Accessible communications applies to all communications that are:

- external and internal
- formal and informal
- major and minor
- generated by the [organization](https://www.w3.org/TR/maturity-model/#dfn-organization) directly or by third parties under contract to the organization

[Accessible communications](https://academic.admin.ox.ac.uk/accessible-communication#collapse1801031) is an umbrella term for clear, direct, and easy-to-understand communications that are renderable in multiple formats so that all users have equivalent access. It considers barriers to accessing information and removes them or provides alternatives.
