### ISSUE TITLE
2.4 Assessment Template Needs Correcting

### ISSUE THREAD

**Issue by Helixopp** [w3c/maturity-model#233]
[2.4 Assessment Template](https://www.w3.org/TR/maturity-model/#assessment-template) needs to be reworded. It incorrectly implies that the experimental spreadsheet prototype is a published method by which this maturity model is intended to be used. In actuality, the experimental spreadsheet prototype is nothing more than an example of how you can document the maturity model evaluation process. This needs to be corrected.  

Current Form:

Organizational ICT Accessibility Maturity is assessed using the Accessibility Maturity Model assessment template. The template contains worksheet tabs specific to each [dimension](https://www.w3.org/TR/maturity-model/#dfn-dimension). The dimension tabs are organized with the dimension definitions and outcomes for each of the four [maturity stages](https://www.w3.org/TR/maturity-model/#dfn-maturity-stage) and provides a list of the dimension’s [proof points](https://www.w3.org/TR/maturity-model/#dfn-proof-point).

**Suggested Text:**

An experimental accessibility maturity model assessment template is provided to assist individuals in documenting their evaluation efforts through the process provided in this Editors Draft. This experimental tool provided by the task force to check the feasibility of the process provided in the Editors Draft.

The assessment template contains worksheet tabs specific to each [dimension](https://www.w3.org/TR/maturity-model/#dfn-dimension). The dimension tabs are organized with the dimension definitions and outcomes for each of the four [maturity stages](https://www.w3.org/TR/maturity-model/#dfn-maturity-stage) and provides a list of the dimension’s [proof points](https://www.w3.org/TR/maturity-model/#dfn-proof-point).

The blank cells below each maturity stage are intended to be completed by the [organization](https://www.w3.org/TR/maturity-model/#dfn-organization) and provide space to document evidence that the organization has reached that stage. The evidence is intended to include progress on [proof point](https://www.w3.org/TR/maturity-model/#dfn-proof-point) completion, or other relevant information that can be used to claim that the outcomes for that stage have been met.

Proof points may span across multiple stages, work being initiated in one stage and completed in a more advanced stage.

EDITOR'S NOTE

The Maturity Model assessment template is intended as a high-fidelity prototype to track the accessibility maturity evaluation process provided in this publication. It was developed in an Excel format. A final published format is to be determined, but is envisioned as HTML. It may also be made available in other downloadable, accessible formats.

EDITOR'S NOTE

This assessment template is experimental and is a work in progress. The [proof point](https://www.w3.org/TR/maturity-model/#dfn-proof-point) in this document may not be in sync with the assessment template.

**Comment by jeffkline** [comment]
Let me call attention to our [APA Maturity Model Task Force page](https://www.w3.org/WAI/about/groups/task-forces/maturity-model/#mission)  and [Work Scope page](https://www.w3.org/WAI/about/groups/task-forces/maturity-model/work-statement/) which clearly state that the assessment tool is in the scope of the group’s mission. I also went back and reviewed the Task Force meeting minutes and could find no record of any notion that the assessment tool was “experimental” or just an “example”.
 
So, unless the scope has somehow changed without our knowledge, we can put to rest the question of whether or not the assessment tool’s  inclusion as integral to the work.
 
There is no precedent that I could find for maturity models, accessibility or otherwise, where the model is does not include a tool / method for progress measurement.
 
As mentioned earlier, the references to the assessment tool in our MM document are completely integrated so it’s not obvious that reference to it or  its inclusion could be backed out without significant compromise to the model and work, which has been published, presented, reviewed, accepted, and viewed very favorably by both w3c members and the public (rightly so!) so it’s not clear why we would want to “throw the baby out with the bath water” when we have a world class, state of the art model / assessment tool.
 
With all that in mind, I do agree that it might not be appropriate to refer to the tool as a prototype, but that is a terminology issue that can be easily resolved. Perhaps referring to the tool it as “beta” version, for example, would accurately depict where we are with the tool and provides us with flexibility as to where we go with it towards a more “final” version. Here is one of many similar examples of the definition:
 
               From Wiktionary :
What is a beta version?
(computing) An early version of a program or application that contains most of the major features, but is not yet complete. Sometimes these versions are released only to a select group of people, or to the general public, for testing and feedback.

**Comment by Helixopp** [comment]
I am not saying that we won’t work on a tool. That tool will be a separate effort from the process document that we publish.

The Editor’s notes clearly warn readers that the spreadsheet is experimental.



This message was Sent from my iPhone. Please excuse any typographic errors.

On Nov 25, 2024, at 9:24 AM, Jeff Kline ***@***.***> wrote:

﻿
Let me call attention to our APA Maturity Model Task Force page and Work Scope page which clearly state that the assessment tool is in the scope of the group’s mission. I also went back and reviewed t
External ***@***.******@***.***>)
  Report This Email<https://protection.inkyphishfence.com/report?id=bmV0b3JnZnQ4NDM0NDAvZGZhemlvQGhlbGl4b3BwLmNvbS9jMWJjOGM4NWQ4NmE5NmYxNTBmOTcwNzFiMDQ2NzE4Ni8xNzMyNTU1NDMzLjg2MTQ0NjY=#key=57cc1b113d5e47c626435a75efd1f375>  FAQ<https://www.godaddy.com/help/report-email-with-advanced-email-security-40813>  GoDaddy Advanced Email Security, Powered by INKY<https://www.inky.com/protection-by-inky>


Let me call attention to our APA Maturity Model Task Force page<https://shared.outlook.inky.com/link?domain=www.w3.org&t=h.eJxNzctuwjAQheFXQWYLmbi-xLCCJU_QtePYiUXCRPZYoa367sVdsT369Z0fVtLMzjs2Ea35DLBtW7OJBtMIn9cb2B4LwZiwrBnI5vsxYHI-w2KppEhfxwUHP8N-iTlHfLDDjt2r9_D0MgIZKaRsYQj2O-Jl8nN84ro2DhdwvHfGGTUYbU86cNWGU9d2vG-l7rjRwDvxoZSSQjRGcym1rrz_55FiiM7S6zNfxkhT6Stag6EGb9PvH-57SKQ.MEUCIAfbnS0aowGaV4alaRBn3-0ZCZ7cmcHhw5LJ0ASRt4oOAiEA3w2qTCxc8vCgJYV15uWeCGfO-92vC4hq7TSbNORo3H4> and Work Scope page<https://shared.outlook.inky.com/link?domain=www.w3.org&t=h.eJxNzD1uxCAQQOGrrKhjjwkYs1ttyj1BaozBRv4ZCwaxSZS7J6RK-_T0fbEcN3a7sIXoTDeAUkpbRItxhve3B5gRM8EcMZ8JyKS18RitS7AbyjHQR7Pj5DYoGNcmkSG3u4OAvVzYWtnD0S_lSUshZQeTN58B74vbwhPPs7W4g-Wj1Vb3k1bmqjzvO38duoGPnVQD1wr4IF77vpdCtFpxKZWqvPvjkYIP1lDAI93nQEseK1qHqQ7_0vcPajhLcw.MEUCIQCeU2IkRu3SV9uo-2JqzllxU6Oe18CYW4mG7d7u8X-gxAIgP-PpHFpdRzYPjAwwc7mOSIgTuxsjW5Zzu0a7KvUNf-s> which clearly state that the assessment tool is in the scope of the group’s mission. I also went back and reviewed the Task Force meeting minutes and could find no record of any notion that the assessment tool was “experimental” or just an “example”.

So, unless the scope has somehow changed without our knowledge, we can put to rest the question of whether or not the assessment tool’s inclusion as integral to the work.

There is no precedent that I could find for maturity models, accessibility or otherwise, where the model is does not include a tool / method for progress measurement.

As mentioned earlier, the references to the assessment tool in our MM document are completely integrated so it’s not obvious that reference to it or its inclusion could be backed out without significant compromise to the model and work, which has been published, presented, reviewed, accepted, and viewed very favorably by both w3c members and the public (rightly so!) so it’s not clear why we would want to “throw the baby out with the bath water” when we have a world class, state of the art model / assessment tool.

With all that in mind, I do agree that it might not be appropriate to refer to the tool as a prototype, but that is a terminology issue that can be easily resolved. Perhaps referring to the tool it as “beta” version, for example, would accurately depict where we are with the tool and provides us with flexibility as to where we go with it towards a more “final” version. Here is one of many similar examples of the definition:

           From Wiktionary :


What is a beta version?
(computing) An early version of a program or application that contains most of the major features, but is not yet complete. Sometimes these versions are released only to a select group of people, or to the general public, for testing and feedback.

**Comment by Helixopp** [comment]
I never said that we shouldn't refer to the spreadsheet as a "prototype". In fact., experimental prototype perfectly describes the role of the spreadsheet: A prototype is a sample design to test out and see if it's any good. A prototype is your test case and may become the model on which to base the design of the finished product.

**Comment by Helixopp** [comment]
This issue is not about whether or not we work on assessment tool. This issue is about whether or not the spreadsheet is the  assessment tool, and it is not. That needs to be clearly stated. As you mention " this is only one option we are putting forth and may ultimately switch from an excel format to something else like HTML etc. and folks can take and update it as they see fit which is exactly what Benetech has done."

**Comment by Helixopp** [comment]
This also speaks to my issue #232 and why references to the spreadsheet should be removed from the process steps

**Comment by Helixopp** [comment]
In support of my reasoning from separating the "assessment spreadsheet" from the prescribed evaluation process I have created a crude demo of how the same results can be achieved from listing information, and links, in a word doc. You could easily assign an arbitrary number value to each proof point and add them up as the spreadsheet does. Ultimately, the word doc achieves the very same goal, proving that the spreadsheet is not inextricably tied to the process. Furthermore, users of the model should be afforded choice in how they document or conduct their evaluation. Yes, the spreadsheet may becomee an option, but should never be the only option. The narrative needs to reflect that. Additionally, the spreadsheet is far from ready to be reliable.d 
[Accessibility Maturity Model Word Document Assessment Demo.docx](https://github.com/user-attachments/files/17966615/Accessibility.Maturity.Model.Word.Document.Assessment.Demo.docx)

**Comment by jeffkline** [comment]
The more correspondence on this "issue" the less I understand what the issue(s) is.


As @clapierre correctly notes:

"Objective: The mission of the Maturity Model Task Force (MMTF) is to craft an Accessibility Maturity Model (AMM) narrative and assessment tool in support of W3C standards..."

These are 2 separate efforts. **<jk> What does this mean? They are both subtasks of the main task mission which includes both the assessment tool and the "informed Maturity Model narrative".  I agree that the tool being developed and refined may not(or may not) end up being a defect final version, but it is crucial that a working tool is released at the same time as the document.  We proposed several alternatives on language that communicates that it may not resemble future versions and we need to decide on what that language is. Without it, there is no useful way for users to do an actual assessment, beyond making up their own, which would be a disaster. <jk>**  

"Statement of Work: The MMTF will develop an informed Maturity Model narrative and an assessment tool that can be used to respond to the narrative ..."

Again, these are 2 separate efforts. The narrative describes the process. **<jk> the narrative describes the model and its components and other elements for clarity and completeness . <jk>**   The tool will be an "option" for users to use, but not a requirement. If it is not a requirement then the narrative should not impose its use through the narrative. It should refer to it as an option to follow the process. **<jk>There is no requirement for any of this as you know. It will be published as a note. With that said,  we can position the most current version at the time of publishing as  a recommended tool / template that can be used until a more permanent one is available. <jk>**

"Now I agree this is only one option we are putting forth and may ultimately switch from an excel format to something else like HTML etc. and folks can take and update it as they see fit which is exactly what Benetech has done." **<jk> agreed <jk>**

@clapierre agrees it is only one option. This issue is about making that clear in the narrative so that we are not telling users that the only way to assess maturity is by using this spreadsheet. **<jk> I think "recommended  would be OK, but there is nothing in the narrative that informs readers  that they can or should create their own tool, which I believe will be neither valuable or helpful in the long run, for reasons I have cited previously. Consistency through standardization is important. <jk>** 

All I am saying is that we reword the narrative to explain exactly what @clapierre just agreed to "this is only one option we are putting forth and may ultimately switch from an excel format to something else like HTML etc. and folks can take and update it as they see fit which is exactly what Benetech has done." **<jk> slight edit...."this is **the task force recommended** option we are putting forth and may ultimately switch from an excel format to something else like HTML etc. " <jk>**
I would disagree with @clapierre "I think for our public release both the document and the "assessment tool" should be in sync or at least not contradict each other. We can always make improvements and update our releases as we evolve and improve both." <jk I agree with @clapierre statement<jk>

If they are 2 separate efforts, they aren't interdependent for publishing. Our disclaimers will be sufficient to explain any contradictions **< jk>  I don't agree. At least for the first official publish, they need to be released together, after that, it would be less problematic to not sync as tightly. <jk>**

**<jk> If I try to go back and understand how all this came about, I recall it was related to an agenda item that I put forward as to how to deal the differences in the proof points in the narrative and assessment tool.... And if they should be synced or not. If yes, the proof points should be aded to the narrative which is not a large task. If no, and we have the "disclaimer" about that in the narrative (per my proposed draft of that language), we are good to go.  

If the team wants to find a different terminology to position the assessment tool  we have been developing together for the past couple of years as not a final version, lets complete that task together and get this over the line.<jk>**

**Comment by swinehartganderson** [comment]
I've missed some conversations, so I hope I'm not muddying the waters or changing topics. 

Looking back at my notes from a year ago and into Jan/Feb of 2024 in the "[Usability] Proof points and evaluation - Issues #43, 85, 89, 78" Google Document that this group was reviewing, shed some light on how the current content started specifying to use the spreadsheet to assess maturity came about. We were looking at resolving GitHub issues. It looks like the basic steps to evaluate a proof point started integrating the spreadsheet as the tool, and then further edits to simplify directions, which made it sound like the spreadsheet was THE TOOL to assess vs. A TOOL. 

Jan/Feb 2024 notes:
Added ‘How to rate and evaluate’ the dimension in each section. 
- The basic steps to evaluate are the same in each section: download the spreadsheet and use the proof points as examples to fill it out
- The definitions of launch, integrate, and optimize are specific to each section, as they use the information from the table.
- This replaces the table at the end.
- Moved the proof points below the ‘how to rate and evaluate’ section, so the directions for how to rate and evaluate that section are shown first.


After 49 revisions and group feedback, the content ended up at (example shown is 3.1.1): 

3.1.1 How to Evaluate Communications’ Maturity Level

1. Download the [maturity model spreadsheet](https://www.w3.org/TR/maturity-model/#assessment-template-excel).
2. List all the organization’s internal and external communication channels, such as email, video conferencing, or social media. 
3. Compare the list to the spreadsheet to decide which proof points will be used to assess your organization’s “Communications” accessibility maturity. Not all proof points will be used for every business or organization. The proof points in section 3.1.2 are non-exhaustive examples of criteria.

**Comment by Helixopp** [comment]
No worries @swinehartganderson. We resolved the issue during today's meeting: https://www.w3.org/2024/12/04-maturity-minutes.html

**Comment by Helixopp** [comment]
Resolution has been completed
