### ISSUE TITLE
Section 3.4.1 Proof Points for ICT Development Lifecycle: Missing planning aspects

### ISSUE THREAD

**Issue by maryjom** [w3c/maturity-model#81]
The proof points for ICT development lifecycle section needs a sub-section on planning. Some things that come to mind:
- Planning process with templates, checklists, and output that ensures accessibility is incorporated 
- Requirements and goals for accessibility of work products are documented and communicated to the team.

**Comment by jeffkline** [comment]
To accommodate this issue, We will change the title Section 3.4.2.2 to Planning and Design, and add a proof point to that section.
Bullet #1 in this section...
- Digital accessibility standards and other related criteria (as identified) are integrated into planning and design phases of ICT development projects.

**Comment by jeffkline** [comment]
Thanks, Jeff. A little premature on closing the issue. We do that after the document update. But it’s ok for now.
Sent from my iPhone

On Jul 3, 2024, at 1:23 PM, Jeff Kline ***@***.***> wrote:

﻿David, I performed the following actions: created the language for the planning proof point closed issue 81. Inserted the new proof point into the assessment tool and modified the scoring on the ICT D
External ***@***.******@***.***>)
 Report This Email<https://protection.inkyphishfence.com/report?id=bmV0b3JnZnQ4NDM0NDAvZGZhemlvQGhlbGl4b3BwLmNvbS9kNzg3NDlkOGUwMmY1NjBjMTMxZTUxZDdiNThhNDk0NS8xNzIwMDM4MTkwLjM=#key=aef8ef52e592eadcc7208d0e939ddb4c>  FAQ<https://www.godaddy.com/help/report-email-with-advanced-email-security-40813>  GoDaddy Advanced Email Security, Powered by INKY<https://www.inky.com/protection-by-inky>

David,

I performed the following actions:

 *   created the language for the planning proof point
 *   closed issue 81.
 *   Inserted the new proof point into the assessment tool and modified the scoring on the ICT Dev tab to include it. The edited version of the spreadsheet is attached

Charles, please proceed at your leisure to modify the document with this additional proof point, and rename / re-upload the revised spreadsheet  (attached) as the newest version.

And thank you for that!

Regards,


[A picture containing text, black, clock  Description automatically generated]<https://shared.outlook.inky.com/link?domain=strategicaccessibility.com&t=h.eJxFzEsOgyAUQNGtGMYNH4WCjtwKwkNfxWKQJrVN997QSac3J_dNHjmSoSFLKfvA2FGyLTCjs87BceCEEctJXdoYuTRkrfQOJeU5FCM7KTnzwb4wjQtEfKZ9_1mvjZa9N8DboK7ciU6AEl5PyljZS8WEbjnvjOg57eoY6vgGIWQ4aaRrxDuM82Yx1l8Vvop_-XwBtVA5YQ.MEQCIBaNTDFkL7I1oHIkoy39L8QnokWcc0hPc5HXhVsvUJgIAiB-0g05Io8SFOZzoefzfSs2FIx6R0U0Pllr1O4s1KWuzQ>
***@***.******@***.***>
5  1  2   .   4  2  6   .   9   7  7  9

From: David Fazio ***@***.******@***.***>>
Date: Wednesday, July 3, 2024 at 11:45 AM
To: w3c/maturity-model ***@***.******@***.***>>
Cc: Jeff Kline ***@***.******@***.***>>, Assign ***@***.******@***.***>>
Subject: Re: [w3c/maturity-model] Section 3.4.1 Proof Points for ICT Development Lifecycle: Missing planning aspects (Issue #81)

Assigned #81<https://shared.outlook.inky.com/link?domain=github.com&t=h.eJxFzEsOgyAUheGtGMatFwQrOnIrKhelohgeaW3TvTd00unJf743Sd6SriBLjEfoAGYTlzSWk9vgwSfYhpi8ied1cwotmBASBpCMXAqy5t-O0flZRym4EBSUHl7G9Qta83TH8XNUIxvRKom00vWNTowzrJlqxloOohU1sKailEvW0pJnGDN8R609nqUtV2t27OdtMDZ7uVC5-C-fL-O3PYU.MEUCIQChr39iDnVO8B23lnO4DecCjgbzmShGvOEahN9hEc0ewAIgX_BcWsMuo94CDugDvJNCYUcQzM41HVUFNSzRrdTMLe4> to @jeffkline<https://shared.outlook.inky.com/link?domain=github.com&t=h.eJxFjcsOgyAUBX_FsG54CBR05a-oXJSKQhSTPtJ_b66bbk_mzHzIuUfSVmQuJR8tY1Mo8znQMa3sAd4vMWxAbhVZENqgpH3yxSqpFGfO9--QuhlieKacr5Mz1qjGWeC113c-CilAC2cGbXvVKM2EqTmXVjScShQDijG1w4tGegW7ae1DRB8SDon_8v0B7HY21w.MEYCIQDKNUEeJR9XSAB_gvi9LJOR30XyYGY_p9-TbsTFn4P7ewIhAPRTX2Mo_8mOjQ-pUytI_g6tzZ6aDJWnkWFxghuAyIHB>.

—
Reply to this email directly, view it on GitHub<https://shared.outlook.inky.com/link?domain=github.com&t=h.eJxFzEESgiAYQOGrOLRNAUFFV14F5UdJEEehsqa7N7Rp--bN90Zxt6jL0BzCdnQYTybMcShG7_CDjdjJEHcTztx5BRab44hwYEEvcIc15JQxUYqS14yia4aWJK0Q_D7pIDjjnGCl5cv4fgZrnn7bfrJqRMNbJYCUuqrJSBmFiqpmqITkLa8wbUpCmKAtKViCIcE30HqHs7DFYs0K_eSksclLh0rHv3y-FlBCMA.MEYCIQD1NRyOj5sQu_FoxhytxjvFYgB1aIDY0Y4z7sCXdIYBhgIhALy_AOF6Q9k3Wr8NdjwfsrxD2K4AnfvtXqXo0F4tB_4l>, or unsubscribe<https://shared.outlook.inky.com/link?domain=github.com&t=h.eJxFj8lugzAARH8l4tyy2Q4kp7AEF4MTJSGAuLGY4IZABEbqov575V46x9HT08y3sky9sl0pnRDPeatpNy66pVLr8aENo-Atr0vBx2HWlmFeqrmeeMVey0V0mpOdaeFFOMOFtT8iP_aRQ_KkiE7UdZ3UOwQXunZk3IgAQhMvfQtN_0LTUxbmIKYpRFfH9UhQ5BjFQZgCHIHkSoo8D80YH4Jz5iGfHFDuZ5QkmEJ_f3Qv-AR8TEPlZaXc5fKBiXG6tcKGAEJda9ryi4-7jvX8Y3w-_540lm3BTWMz3WzRWq8NYDBkNFaF7BJuINIMy9R1YBsbXQVSzKT4nbXtxD7VXr33fGC726PkvfRJopHEf_PzC2FdY6Q.MEUCIQDBC7lUnqo7Wko6JtFizT2-swavQoYUlnwhEeFVTcFDJQIgFSr5hcqL3NefIGLUEF3b9TXbQPUu5FHE4reWqK5I08w>.
You are receiving this because you were assigned.Message ID: ***@***.******@***.***>>
[cid:16%253aX%253aRgAAAADOgoTO3gq3T7lYVuzapIA8BwCxc1j9JlcUTa4laROD9ctZAAAAAAEMAACxc1j9JlcUTa4laROD9ctZAAgwNMMHAAAJ%253aEAAWwN5z1dfdTZ6FtXBuiOjj]
<A11yMaturityTemplate with ICT dev dimension new proofpoint.xlsx>

**Comment by jeffkline** [comment]
Oh. Sorry. I thought the commitment to change with the solution Was enough to close out an issue.

Anyway, whenever the changes get pushed up, we can close it out

**Comment by jeffkline** [comment]
Hi Jeff and all,

I have added Jeff's changes and created a pull request.

Jeff, FYI, you updated the totals from 25 to 26, however you forgot to include the proof point Sum: B12-B41, D12-D41, etc. so, all of the totals would have missed the first proof point you added.

Also, we need to update the Cover page when we make changes to the template under list of Changes with the date of the change made.


I made those changes and then copied all that over to the other "Filled In Example Template"

Ready for review and Merge.


Thanks

Charles

EOM



________________________________
